services:
  chatbot_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive

    image: "ragmodels"
    container_name: luna
    privileged: true
    restart: on-failure
    ports:
      - "8000:8000"

    # volumes:
    #   - ./data:/app/data
    #   - ./scripts:/app/scripts
    #   - /etc/timezone:/etc/timezone
    #   - /etc/localtime:/etc/localtime

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    working_dir: /app/scripts
    # command: ["chainlit", "run", "main.py", "-w"]
    # command: sleep infinity
    command: ["chainlit", "run", "main.py", "-w", "--host","0.0.0.0", "--port", "8000"]
